getwd()

dataTable <- read.table(
  "drug_consumption.data", 
  sep=",", header=FALSE)

View(dataTable)

colnames(dataTable) <- c("ID", "Age","Gender","Education","Country","Ethnicity","NScore",
                         "Escore","Oscore","Ascore","Cscore","Impulsive","SS","Alcohol",
                         "Amphet","Amyl","Benzos","Caff","Cannabis","Choc","Coke",
                         "Crack","Ecstasy","Heroin","Ketamine","Legalh","LSD","Meth",
                         "Mushrooms","Nicotine","Semer","VSA")

library(plyr)
dataTable$Age <- as.factor(dataTable$Age)
dataTable$Age <- revalue(dataTable$Age, c("-0.95197"="18-24"))
dataTable$Age <- revalue(dataTable$Age, c("-0.07854"="25-34"))
dataTable$Age <- revalue(dataTable$Age, c("0.49788"="35-44"))
dataTable$Age <- revalue(dataTable$Age, c("1.09449"="45-54"))
dataTable$Age <- revalue(dataTable$Age, c("1.82213"="55-64"))
dataTable$Age <- revalue(dataTable$Age, c("2.59171"="65-74"))

dataTable$Gender <- as.factor(dataTable$Gender)
dataTable$Gender <- revalue(dataTable$Gender, c("0.48246"="Female"))
dataTable$Gender <- revalue(dataTable$Gender, c("-0.48246"="Male"))

dataTable$Education <- as.factor(dataTable$Education)
dataTable$Education <- revalue(dataTable$Education, c("-2.43591"="Left school before 16 years"))
dataTable$Education <- revalue(dataTable$Education, c("-1.7379"="Left school at 16 years"))
dataTable$Education <- revalue(dataTable$Education, c("-1.43719"="Left school at 17 years"))
dataTable$Education <- revalue(dataTable$Education, c("-1.22751"="Left school at 18 years"))
dataTable$Education <- revalue(dataTable$Education, c("-0.61113"="Some college or university, no certificate or degree"))
dataTable$Education <- revalue(dataTable$Education, c("-0.05921"="Professional certificate/ diploma"))
dataTable$Education <- revalue(dataTable$Education, c("0.45468"="University degree"))
dataTable$Education <- revalue(dataTable$Education, c("1.16365"="Masters degree"))
dataTable$Education <- revalue(dataTable$Education, c("1.98437"="Doctorate degree"))


dataTable$Country <- as.factor(dataTable$Country)
dataTable$Country <- revalue(dataTable$Country, c("-0.09765"="Australia"))
dataTable$Country <- revalue(dataTable$Country, c("0.24923"="Canada"))
dataTable$Country <- revalue(dataTable$Country, c("-0.46841"="New Zealand"))
dataTable$Country <- revalue(dataTable$Country, c("-0.28519"="Other"))
dataTable$Country <- revalue(dataTable$Country, c("0.21128"="Republic of Ireland"))
dataTable$Country <- revalue(dataTable$Country, c("0.96082"="UK"))
dataTable$Country <- revalue(dataTable$Country, c("-0.57009"="USA"))


dataTable$Ethnicity <- as.factor(dataTable$Ethnicity)
dataTable$Ethnicity <- revalue(dataTable$Ethnicity, c("-0.50212"="Asian"))
dataTable$Ethnicity <- revalue(dataTable$Ethnicity, c("-1.10702"="Black"))
dataTable$Ethnicity <- revalue(dataTable$Ethnicity, c("1.90725"="Mixed-Black/Asian"))
dataTable$Ethnicity <- revalue(dataTable$Ethnicity, c("0.126"="Mixed-White/Asian"))
dataTable$Ethnicity <- revalue(dataTable$Ethnicity, c("-0.22166"="Mixed-White/Black"))
dataTable$Ethnicity <- revalue(dataTable$Ethnicity, c("0.1144"="Other"))
dataTable$Ethnicity <- revalue(dataTable$Ethnicity, c("-0.31685"="White"))


dataTable$VSA <- revalue(dataTable$VSA, c("CL0"="Never Used"))
dataTable$VSA <- revalue(dataTable$VSA, c("CL1"="Used over a Decade Ago"))
dataTable$VSA <- revalue(dataTable$VSA, c("CL2"="Used in Last Decade"))
dataTable$VSA <- revalue(dataTable$VSA, c("CL3"="Used in Last Year"))
dataTable$VSA <- revalue(dataTable$VSA, c("CL4"="Used in Last Month"))
dataTable$VSA <- revalue(dataTable$VSA, c("CL5"="Used in Last Week"))
dataTable$VSA <- revalue(dataTable$VSA, c("CL6"="Used in Last Day"))
dataTable$VSA <- as.factor(dataTable$VSA)

dataTable$Semer <- revalue(dataTable$Semer, c("CL0"="Never Used"))
dataTable$Semer <- as.factor(dataTable$Semer)

dataTable$Nicotine <- revalue(dataTable$Nicotine, c("CL0"="Never Used"))
dataTable$Nicotine <- revalue(dataTable$Nicotine, c("CL1"="Used over a Decade Ago"))
dataTable$Nicotine <- revalue(dataTable$Nicotine, c("CL2"="Used in Last Decade"))
dataTable$Nicotine <- revalue(dataTable$Nicotine, c("CL3"="Used in Last Year"))
dataTable$Nicotine <- revalue(dataTable$Nicotine, c("CL4"="Used in Last Month"))
dataTable$Nicotine <- revalue(dataTable$Nicotine, c("CL5"="Used in Last Week"))
dataTable$Nicotine <- revalue(dataTable$Nicotine, c("CL6"="Used in Last Day"))
dataTable$Nicotine <- as.factor(dataTable$Nicotine)

dataTable$Mushrooms <- revalue(dataTable$Mushrooms, c("CL0"="Never Used"))
dataTable$Mushrooms <- revalue(dataTable$Mushrooms, c("CL1"="Used over a Decade Ago"))
dataTable$Mushrooms <- revalue(dataTable$Mushrooms, c("CL2"="Used in Last Decade"))
dataTable$Mushrooms <- revalue(dataTable$Mushrooms, c("CL3"="Used in Last Year"))
dataTable$Mushrooms <- revalue(dataTable$Mushrooms, c("CL4"="Used in Last Month"))
dataTable$Mushrooms <- revalue(dataTable$Mushrooms, c("CL5"="Used in Last Week"))
dataTable$Mushrooms <- revalue(dataTable$Mushrooms, c("CL6"="Used in Last Day"))
dataTable$Mushrooms <- as.factor(dataTable$Mushrooms)

dataTable$Meth <- revalue(dataTable$Meth, c("CL0"="Never Used"))
dataTable$Meth <- revalue(dataTable$Meth, c("CL1"="Used over a Decade Ago"))
dataTable$Meth <- revalue(dataTable$Meth, c("CL2"="Used in Last Decade"))
dataTable$Meth <- revalue(dataTable$Meth, c("CL3"="Used in Last Year"))
dataTable$Meth <- revalue(dataTable$Meth, c("CL4"="Used in Last Month"))
dataTable$Meth <- revalue(dataTable$Meth, c("CL5"="Used in Last Week"))
dataTable$Meth <- revalue(dataTable$Meth, c("CL6"="Used in Last Day"))
dataTable$Meth <- as.factor(dataTable$Meth)

dataTable$LSD <- revalue(dataTable$LSD, c("CL0"="Never Used"))
dataTable$LSD <- revalue(dataTable$LSD, c("CL1"="Used over a Decade Ago"))
dataTable$LSD <- revalue(dataTable$LSD, c("CL2"="Used in Last Decade"))
dataTable$LSD <- revalue(dataTable$LSD, c("CL3"="Used in Last Year"))
dataTable$LSD <- revalue(dataTable$LSD, c("CL4"="Used in Last Month"))
dataTable$LSD <- revalue(dataTable$LSD, c("CL5"="Used in Last Week"))
dataTable$LSD <- revalue(dataTable$LSD, c("CL6"="Used in Last Day"))
dataTable$LSD <- as.factor(dataTable$LSD)

dataTable$Legalh <- revalue(dataTable$Legalh, c("CL0"="Never Used"))
dataTable$Legalh <- revalue(dataTable$Legalh, c("CL1"="Used over a Decade Ago"))
dataTable$Legalh <- revalue(dataTable$Legalh, c("CL2"="Used in Last Decade"))
dataTable$Legalh <- revalue(dataTable$Legalh, c("CL3"="Used in Last Year"))
dataTable$Legalh <- revalue(dataTable$Legalh, c("CL4"="Used in Last Month"))
dataTable$Legalh <- revalue(dataTable$Legalh, c("CL5"="Used in Last Week"))
dataTable$Legalh <- revalue(dataTable$Legalh, c("CL6"="Used in Last Day"))
dataTable$Legalh <- as.factor(dataTable$Legalh)

dataTable$Ketamine <- revalue(dataTable$Ketamine, c("CL0"="Never Used"))
dataTable$Ketamine <- revalue(dataTable$Ketamine, c("CL1"="Used over a Decade Ago"))
dataTable$Ketamine <- revalue(dataTable$Ketamine, c("CL2"="Used in Last Decade"))
dataTable$Ketamine <- revalue(dataTable$Ketamine, c("CL3"="Used in Last Year"))
dataTable$Ketamine <- revalue(dataTable$Ketamine, c("CL4"="Used in Last Month"))
dataTable$Ketamine <- revalue(dataTable$Ketamine, c("CL5"="Used in Last Week"))
dataTable$Ketamine <- revalue(dataTable$Ketamine, c("CL6"="Used in Last Day"))
dataTable$Ketamine <- as.factor(dataTable$Ketamine)

dataTable$Heroin <- revalue(dataTable$Heroin, c("CL0"="Never Used"))
dataTable$Heroin <- revalue(dataTable$Heroin, c("CL1"="Used over a Decade Ago"))
dataTable$Heroin <- revalue(dataTable$Heroin, c("CL2"="Used in Last Decade"))
dataTable$Heroin <- revalue(dataTable$Heroin, c("CL3"="Used in Last Year"))
dataTable$Heroin <- revalue(dataTable$Heroin, c("CL4"="Used in Last Month"))
dataTable$Heroin <- revalue(dataTable$Heroin, c("CL5"="Used in Last Week"))
dataTable$Heroin <- revalue(dataTable$Heroin, c("CL6"="Used in Last Day"))
dataTable$Heroin <- as.factor(dataTable$Heroin)

dataTable$Ecstasy <- revalue(dataTable$Ecstasy, c("CL0"="Never Used"))
dataTable$Ecstasy <- revalue(dataTable$Ecstasy, c("CL1"="Used over a Decade Ago"))
dataTable$Ecstasy <- revalue(dataTable$Ecstasy, c("CL2"="Used in Last Decade"))
dataTable$Ecstasy <- revalue(dataTable$Ecstasy, c("CL3"="Used in Last Year"))
dataTable$Ecstasy <- revalue(dataTable$Ecstasy, c("CL4"="Used in Last Month"))
dataTable$Ecstasy <- revalue(dataTable$Ecstasy, c("CL5"="Used in Last Week"))
dataTable$Ecstasy <- revalue(dataTable$Ecstasy, c("CL6"="Used in Last Day"))
dataTable$Ecstasy <- as.factor(dataTable$Ecstasy)

dataTable$Crack <- revalue(dataTable$Crack, c("CL0"="Never Used"))
dataTable$Crack <- revalue(dataTable$Crack, c("CL1"="Used over a Decade Ago"))
dataTable$Crack <- revalue(dataTable$Crack, c("CL2"="Used in Last Decade"))
dataTable$Crack <- revalue(dataTable$Crack, c("CL3"="Used in Last Year"))
dataTable$Crack <- revalue(dataTable$Crack, c("CL4"="Used in Last Month"))
dataTable$Crack <- revalue(dataTable$Crack, c("CL5"="Used in Last Week"))
dataTable$Crack <- revalue(dataTable$Crack, c("CL6"="Used in Last Day"))
dataTable$Crack <- as.factor(dataTable$Crack)

dataTable$Coke <- revalue(dataTable$Coke, c("CL0"="Never Used"))
dataTable$Coke <- revalue(dataTable$Coke, c("CL1"="Used over a Decade Ago"))
dataTable$Coke <- revalue(dataTable$Coke, c("CL2"="Used in Last Decade"))
dataTable$Coke <- revalue(dataTable$Coke, c("CL3"="Used in Last Year"))
dataTable$Coke <- revalue(dataTable$Coke, c("CL4"="Used in Last Month"))
dataTable$Coke <- revalue(dataTable$Coke, c("CL5"="Used in Last Week"))
dataTable$Coke <- revalue(dataTable$Coke, c("CL6"="Used in Last Day"))
dataTable$Coke <- as.factor(dataTable$Coke)

dataTable$Choc <- revalue(dataTable$Choc, c("CL0"="Never Used"))
dataTable$Choc <- revalue(dataTable$Choc, c("CL1"="Used over a Decade Ago"))
dataTable$Choc <- revalue(dataTable$Choc, c("CL2"="Used in Last Decade"))
dataTable$Choc <- revalue(dataTable$Choc, c("CL3"="Used in Last Year"))
dataTable$Choc <- revalue(dataTable$Choc, c("CL4"="Used in Last Month"))
dataTable$Choc <- revalue(dataTable$Choc, c("CL5"="Used in Last Week"))
dataTable$Choc <- revalue(dataTable$Choc, c("CL6"="Used in Last Day"))
dataTable$Choc <- as.factor(dataTable$Choc)

dataTable$Cannabis <- revalue(dataTable$Cannabis, c("CL0"="Never Used"))
dataTable$Cannabis <- revalue(dataTable$Cannabis, c("CL1"="Used over a Decade Ago"))
dataTable$Cannabis <- revalue(dataTable$Cannabis, c("CL2"="Used in Last Decade"))
dataTable$Cannabis <- revalue(dataTable$Cannabis, c("CL3"="Used in Last Year"))
dataTable$Cannabis <- revalue(dataTable$Cannabis, c("CL4"="Used in Last Month"))
dataTable$Cannabis <- revalue(dataTable$Cannabis, c("CL5"="Used in Last Week"))
dataTable$Cannabis <- revalue(dataTable$Cannabis, c("CL6"="Used in Last Day"))
dataTable$Cannabis <- as.factor(dataTable$Cannabis)

dataTable$Caff <- revalue(dataTable$Caff, c("CL0"="Never Used"))
dataTable$Caff <- revalue(dataTable$Caff, c("CL1"="Used over a Decade Ago"))
dataTable$Caff <- revalue(dataTable$Caff, c("CL2"="Used in Last Decade"))
dataTable$Caff <- revalue(dataTable$Caff, c("CL3"="Used in Last Year"))
dataTable$Caff <- revalue(dataTable$Caff, c("CL4"="Used in Last Month"))
dataTable$Caff <- revalue(dataTable$Caff, c("CL5"="Used in Last Week"))
dataTable$Caff <- revalue(dataTable$Caff, c("CL6"="Used in Last Day"))
dataTable$Caff <- as.factor(dataTable$Caff)

dataTable$Benzos <- revalue(dataTable$Benzos, c("CL0"="Never Used"))
dataTable$Benzos <- revalue(dataTable$Benzos, c("CL1"="Used over a Decade Ago"))
dataTable$Benzos <- revalue(dataTable$Benzos, c("CL2"="Used in Last Decade"))
dataTable$Benzos <- revalue(dataTable$Benzos, c("CL3"="Used in Last Year"))
dataTable$Benzos <- revalue(dataTable$Benzos, c("CL4"="Used in Last Month"))
dataTable$Benzos <- revalue(dataTable$Benzos, c("CL5"="Used in Last Week"))
dataTable$Benzos <- revalue(dataTable$Benzos, c("CL6"="Used in Last Day"))
dataTable$Benzos <- as.factor(dataTable$Benzos)

dataTable$Amyl <- revalue(dataTable$Amyl, c("CL0"="Never Used"))
dataTable$Amyl <- revalue(dataTable$Amyl, c("CL1"="Used over a Decade Ago"))
dataTable$Amyl <- revalue(dataTable$Amyl, c("CL2"="Used in Last Decade"))
dataTable$Amyl <- revalue(dataTable$Amyl, c("CL3"="Used in Last Year"))
dataTable$Amyl <- revalue(dataTable$Amyl, c("CL4"="Used in Last Month"))
dataTable$Amyl <- revalue(dataTable$Amyl, c("CL5"="Used in Last Week"))
dataTable$Amyl <- revalue(dataTable$Amyl, c("CL6"="Used in Last Day"))
dataTable$Amyl <- as.factor(dataTable$Amyl)

dataTable$Amphet <- revalue(dataTable$Amphet, c("CL0"="Never Used"))
dataTable$Amphet <- revalue(dataTable$Amphet, c("CL1"="Used over a Decade Ago"))
dataTable$Amphet <- revalue(dataTable$Amphet, c("CL2"="Used in Last Decade"))
dataTable$Amphet <- revalue(dataTable$Amphet, c("CL3"="Used in Last Year"))
dataTable$Amphet <- revalue(dataTable$Amphet, c("CL4"="Used in Last Month"))
dataTable$Amphet <- revalue(dataTable$Amphet, c("CL5"="Used in Last Week"))
dataTable$Amphet <- revalue(dataTable$Amphet, c("CL6"="Used in Last Day"))
dataTable$Amphet <- as.factor(dataTable$Amphet)

dataTable$Alcohol <- revalue(dataTable$Alcohol, c("CL0"="Never Used"))
dataTable$Alcohol <- revalue(dataTable$Alcohol, c("CL1"="Used over a Decade Ago"))
dataTable$Alcohol <- revalue(dataTable$Alcohol, c("CL2"="Used in Last Decade"))
dataTable$Alcohol <- revalue(dataTable$Alcohol, c("CL3"="Used in Last Year"))
dataTable$Alcohol <- revalue(dataTable$Alcohol, c("CL4"="Used in Last Month"))
dataTable$Alcohol <- revalue(dataTable$Alcohol, c("CL5"="Used in Last Week"))
dataTable$Alcohol <- revalue(dataTable$Alcohol, c("CL6"="Used in Last Day"))
dataTable$Alcohol <- as.factor(dataTable$Alcohol)

names(dataTable)
hist(dataTable$Country)